### PR TITLE
Fixed N_REPLICA config params error

### LINKED ISSUE #45: .serve_model() throws error while serving MPC model on the grid platform
## Description
Tutorial: [Grid as a Secure MLaaS ](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/grid/Part%2002%20-%20Grid%20as%20a%20Secure%20MLaaS%20to%20Cloud%20Providers.ipynb)

While serving the model, this error is thrown:
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

in line:
cloud_grid_service.serve_model(model,id=model.id,allow_remote_inference=True, mpc=True)

## How to Reproduce
1. Setup grid network(PyGridNetwork) and nodes(PyGridNode).
2. Create a model which extends Plan Parent Class.
3. Serve the model

## Expected Behavior
It should split the model weights into pieces by distributing it through grid network.

## System Information
 - OS: Linux(Ubuntu)
 - OS: 20.4
 - Language Version: Python 3.8.3
 - Package Manager Version: Conda 4.6.11
 - Browser: Google Chrome

### PR DESCRIPTION
**Pull request by shashigharti**
1. set default value for config object(dict) if key doesn't exist.

## Description
Tutorial: Grid as a Secure MLaaS

While serving the model, this error is thrown:
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

in line:
cloud_grid_service.serve_model(model,id=model.id,allow_remote_inference=True, mpc=True)

closes #45 

## How has this been tested?
- The .serve_model() executes without error. 
- The param is set to 1 when the "N_REPLICA" key is not set in config object.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests (Does not Apply)

### CODE REVIEW

**Comment by jmaunon** [comment]
Thanks a lot for your contribution!
Could you include some testing? Our coverage is quite low, for that reason we find some unexpected issues like this one

**Comment by shashigharti** [comment]
Thanks, I am happy to contribute! . Sure I will add the test as well.

**Comment by shashigharti** [comment]
@IonesioJunior @jmaunon  I have added tests also. 

Similar change(in my first commit) was merged in this pull request so I got conflict and have resolved it.
https://github.com/OpenMined/PyGridNetwork/commit/1d09dbe306c5026e867bbf9f6fdc8175ee2fffe1

**Comment by jmaunon** [comment]
Good job!!

**Pull request merged**
